# jenkins-casc.yaml
jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
        - id: "dev"
          password: "dev"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Job/Build:dev"
        - "Job/Cancel:dev"
        - "Job/Read:dev"
        - "Job/Workspace:dev"
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
        - "Run/Replay:dev"
        - "Run/Update:dev"
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
unclassified:
  simple-theme-plugin:
    elements:
      - cssUrl:
          url: "https://cdn.jsdelivr.net/gh/afonsof/jenkins-material-theme@gh-pages/dist/material-cyan.css"
jobs:
  - file: /usr/local/Hackathon.groovy